### ISSUE TITLE
[BUG] cannot run 2.9 docker compose

### ISSUE THREAD

**Issue by fian46** [keitaroinc/docker-ckan#138] opened 2024-10-30 02:51 UTC
**Describe the bug**
i am trying to run the 2.9 docker compose but the ckan container is stopped because the posgres is failed to initialized

**Docker images affected**
1. CKAN 2.9
here is the log before posgres died
![image](https://github.com/user-attachments/assets/b28760fe-9b31-4a48-92f4-ffb21c4d0783)
here is ckan log when it trying to connect to falling posgres
![image](https://github.com/user-attachments/assets/4f72b63a-9fca-430e-82ca-7f7be386a915)

**Comment by stojanovskis1** [comment] 2024-11-01 15:10
@fian46 can you please provide more details i am not able to reproduce this

**Comment by fian46** [comment] 2024-11-01 15:19
I just clone the repo and change directory to 2.9.
After that i run docker compose build && docker compose up -d

I am using desktop docker for windows and those command is running with PowerShell 

After 30 second the posgrest died and followed by ckan. The logs is kike above. I Hope it helps.

**Comment by fian46** [comment] 2024-11-04 03:24
yeah i found the problem if the file is renamed to create_datastore.sh instead of 00_create_datastore.sh. from the logs it shows cannot find file 00_create_datastore.sh

**Comment by stojanovskis1** [comment] 2024-11-04 07:31
@fian46 can we close this issue then?

**Comment by fian46** [comment] 2024-11-04 07:43
Yes we can close this

**Closed** 2024-11-04 08:30 UTC
