### ISSUE TITLE
[BUG] I facing datapusher cann't read .xlsx file

### ISSUE THREAD

**Issue by Doonkung** [keitaroinc/docker-ckan#40] opened 2021-02-10 02:27 UTC
**Describe the bug**
Hello sir, I get the problem when i upload .xlsx file to datastore it's stuck pending  a long time
![image](https://user-images.githubusercontent.com/46586592/107455063-bca75180-6b80-11eb-81b5-c0ba4fa83295.png)

and i found error at log's datapusher like this
![image](https://user-images.githubusercontent.com/46586592/107455246-190a7100-6b81-11eb-9e45-0f9859ba0705.png)

**Docker images affected**
Datapusher images version 0.0.17

**Comment by mbocevski** [comment] 2021-02-10 12:47
This is an upstream problem with `messytables` which is used by datapusher for reading the data from tabular based files. The issue is with XLRD https://github.com/okfn/messytables/blob/3366a08e06ca19abcdb6c624069e1d28414a3363/messytables/excel.py#L42-L53

So it needs to be fixed within messytables.

Workaround is to conver the xlsx file in xls or csv format before uploading.

**Closed by mbocevski** 2021-02-10 12:47 UTC
